export const API_ERROR_CODES = {
  // Authentication
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',

  // Registration
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  PASSWORDS_DO_NOT_MATCH: 'PASSWORDS_DO_NOT_MATCH',

  // Token
  INVALID_TOKEN: 'INVALID_TOKEN',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',

  // Users
  USERNAME_ALREADY_TAKEN: 'USERNAME_ALREADY_TAKEN',
} as const;

export const REGISTER_ERROR_MESSAGES: Record<string, string> = {
  [API_ERROR_CODES.EMAIL_ALREADY_EXISTS]: 'Este email já está cadastrado.',
  [API_ERROR_CODES.USERNAME_ALREADY_EXISTS]: 'Este username já está em uso.',
  [API_ERROR_CODES.PASSWORDS_DO_NOT_MATCH]: 'As senhas não coincidem.',
  [API_ERROR_CODES.EMAIL_NOT_VERIFIED]: 'Conta com este email ainda não verificada.',
};
