export const API_ERROR_CODES = {
  // Authentication
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  USE_GOOGLE_LOGIN: 'USE_GOOGLE_LOGIN',
  INVALID_GOOGLE_TOKEN: 'INVALID_GOOGLE_TOKEN',

  // Registration
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  PASSWORDS_DO_NOT_MATCH: 'PASSWORDS_DO_NOT_MATCH',

  // Token
  INVALID_TOKEN: 'INVALID_TOKEN',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',

  // Users
  USERNAME_ALREADY_TAKEN: 'USERNAME_ALREADY_TAKEN',

  // Email
  EMAIL_SEND_ERROR: 'EMAIL_SEND_ERROR',
  EMAIL_AUTH_ERROR: 'EMAIL_AUTH_ERROR',

  // Members
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_MEMBER: 'USER_ALREADY_MEMBER',
  USER_NOT_IN_WORKSPACE: 'USER_NOT_IN_WORKSPACE',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',

  // General
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',

  // Resources
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  BOARD_NOT_FOUND: 'BOARD_NOT_FOUND',
  LIST_NOT_FOUND: 'LIST_NOT_FOUND',
  CARD_NOT_FOUND: 'CARD_NOT_FOUND',
  INVALID_MOVE: 'INVALID_MOVE',
} as const;

export const REGISTER_ERROR_MESSAGES: Record<string, string> = {
  [API_ERROR_CODES.EMAIL_ALREADY_EXISTS]: 'Este email já está cadastrado.',
  [API_ERROR_CODES.USERNAME_ALREADY_EXISTS]: 'Este username já está em uso.',
  [API_ERROR_CODES.PASSWORDS_DO_NOT_MATCH]: 'As senhas não coincidem.',
  [API_ERROR_CODES.EMAIL_NOT_VERIFIED]: 'Conta com este email ainda não verificada.',
};
