export const APP_CONFIG = {
  PAGINATION: {
    DEFAULT_PAGE_SIZE: 10,
    PAGE_SIZE_OPTIONS: [5, 10, 20, 50],
  },
  VALIDATION: {
    PASSWORD_MIN_LENGTH: 8,
    TITLE_MIN_LENGTH: 3,
    DESCRIPTION_MIN_LENGTH: 10,
  },
} as const;
